services:
  web:
    image: ghcr.io/mdtha-x/rosetta-for-all:latest
    restart: always
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - rosetta-data:/app/data

volumes:
  rosetta-data:
