services:
  client:
    image: ghcr.io/${GITHUB_REPOSITORY:-mdtha-x/rosetta-for-all}-client:latest
    build: ./client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    image: ghcr.io/${GITHUB_REPOSITORY:-mdtha-x/rosetta-for-all}-server:latest
    build: ./server
    restart: always
    expose:
      - "3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/rosetta
    depends_on:
      - mongodb
    volumes:
      - rosetta-data:/app/data

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  rosetta-data:
  mongo-data:
